version: '3'
services:
  elasticsearch:
    user: "1000"
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
    volumes:
      - .devel/elasticsearch/data:/usr/share/elasticsearch/data:z
      - .devel/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"      
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: efk.elasticsearch
    depends_on:
      - fluentd        
  kibana:
    user: "1000"
    image: docker.elastic.co/kibana/kibana-oss:6.0.0
    volumes:
      - .devel/kibana/config:/usr/share/kibana/config:z
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      - fluentd
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: efk.kibana  
  fluentd:
    build:
      context: .devel/fluentd
    volumes:
      - .devel/fluentd/conf:/fluentd/etc:z
    ports:
      - "24224:24224"
      - "24224:24224/udp"
